import os
from sqlalchemy import create_engine

DEBUG_MODE = os.getenv("DEBUG_MODE")

DATABASE_DIALECT = os.getenv("DATABASE_DIALECT")
DATABASE_HOSTNAME = os.getenv("DATABASE_HOSTNAME")
DATABASE_NAME = os.getenv("DATABASE_NAME")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")
DATABASE_PORT = os.getenv("DATABASE_PORT")
DATABASE_USERNAME = os.getenv("DATABASE_USERNAME")

DATABASE_URL = f"{DATABASE_DIALECT}://{DATABASE_USERNAME}:{DATABASE_PASSWORD}@{DATABASE_HOSTNAME}:{DATABASE_PORT}"

print(DATABASE_DIALECT)

Engine = create_engine(
  DATABASE_URL, echo=DEBUG_MODE, future=True
)
